mysql:
  url: "127.0.0.1:3306"         # MySQL
  database: "데이터베이스 이름"    # DB 이름
  user: "root"                  # DB 사용자 이름
  password: "123qwe!@#"         # DB 비밀번호

spring_boot:
  port: 8080                          # SpringBoot 포트
  host: "localhost"                   # SpringBoot 호스트트
  spring_url: "http://localhost:8080" # SpringBoot URL

server:
  port: 8081                          # Go서버 포트
  host: "localhost"                   # Go서버 호스트
  go_url: "http://localhost:8081"     # Go서버 URL

# 키 생성시 사용자에 맞게 개인키, 공개키 파일경로 수정됨. 
ecdsa:
  private_key_path: "C:\Users\jiuk0\Downloads\PrivateKey.json" # 개인키 파일경로
  public_key_path: "C:\Users\jiuk0\Downloads\PublicKey.json"   # 공개키 파일경로